### ISSUE TITLE
add dot notation for err messages for nested fields.

### ISSUE THREAD

**Issue by mkorolyov** [gojuno/genval#16]
By default Validate() method will be generated with fields names equal to struct field names.

Also -tags flag will be added, that will accept comma separated list of tags, like `-tags json,xml`.
For each tag will be generated separate validate method with name `Validate<tag_in_upper_case>`.

So if we set `-tags json,xml` 3 methods will be generated:
* Validate()
* ValidateJSON()
* ValidateXML()

Difference will be only in err msg fields naming. e.g. `ValidateJSON` will use `json` tag field names.

**Comment by mkorolyov** [comment]
@mguzelevich @mkabischev @yauhen-l @hexdigest @l1va 
Hi guys, pls review short spec for change, if no concerns i will start to implement it.

**Comment by yauhen-l** [comment]
I am ok with proposal.
Custom tag can contain complex values. For example `json:"x,omitempty"` or `bson:"[<key>][,<flag1>[,<flag2>]]"` (https://godoc.org/labix.org/v2/mgo/bson#Unmarshal)
Let's define behavior in such cases.

**Comment by mkorolyov** [comment]
@yauhen-l  i will skip all flags, so `json:"x,omitempty"` will be parsed as `x`.

**Comment by hexdigest** [comment]
Don't forget that you can have broken chains i.e. struct A has a field of
type B which is also a struct type but field in struct A doesn't have a
inline tag and you get an error for the B's field. Should we detect such
broken chains and stop generation until tags are fixed?

21 июня 2017 г. 12:37 PM пользователь "Maxim Korolyov" <
notifications@github.com> написал:

**Comment by hexdigest** [comment]
I propose to generate validate("xml") method that will allow you to
generate error messages for the specific tag. Because obviously you can't
generate methods for all known formats.

21 июня 2017 г. 12:37 PM пользователь "Maxim Korolyov" <
notifications@github.com> написал:

**Comment by mkorolyov** [comment]
@hexdigest 

> Don't forget that you can have broken chains i.e. struct A has a field of
> type B which is also a struct type but field in struct A doesn't have a
> inline tag and you get an error for the B's field. Should we detect such
> broken chains and stop generation until tags are fixed?

Is such case at the moment i use struct field name.

> I propose to generate validate("xml") method that will allow you to
> generate error messages for the specific tag. Because obviously you can't
> generate methods for all known formats.

I don't need to generate methods for all known formats, only for those, which will be specified in `tags` flag.

**Comment by hexdigest** [comment]
> Is such case at the moment i use struct field name.

I think we need to generate a warning or even stop the generation.
I'm ok with current solution though.

**Comment by l1va** [comment]
I don't like names, ValidateJSON does not say for me that returning errors will be with field names from json tag. Think once again please. 
As i understand if you want to change only one field for one struct no matter you will generate methods for all structs in pkg. Is it good?  
And how you will call ValidateJSON() ? only manually?

**Comment by mkorolyov** [comment]
Alternatives for ValidateJSON?

Didn't get what you mean in 
> As i understand if you want to change only one field for one struct no matter you will generate methods for all structs in pkg. Is it good?

> And how you will call ValidateJSON() ? only manually?
same as Validate(). manually in ms_core.

**Comment by l1va** [comment]
oh, sorry for delay. 
1. ValidateWithNameFromJsonTag()  ?
2. What problem are you trying to solve? If you want change behavior for all structs in pkg, then you do not need in Validate() method, if you want to change behavior only for some fields - use tags on fields.
3. in ms_core - it means you will change behavior for all ?
4. if struct with 5 fields have only one field with json tag, for others you will use fieldnames?

**Comment by mkabischev** [comment]
> 1. ValidateWithNameFromJsonTag()

It\`s too long and looks like java-style.
> 2. What problem are you trying to solve? If you want change behavior for all structs in pkg, then you do not need in Validate() method, if you want to change behavior only for some fields - use tags on fields.

The main idea is to return errors to client with same names he sent. Imagine you send:
```json
{
    "name": "Mike",
   "age": -10
}
```

And despite you have struct for this request:
```go
type User struct {
    Name string `json:"name"`
    Age int `json:"age" validate:"min=0"`
}
```

We have to return errors like:
```json
{
    "errors": {
        "age": "must be greater than 0"
   }
}
```
> 4. if struct with 5 fields have only one field with json tag, for others you will use fieldnames?

Exactly, because json marshaller does the same.

**Comment by mkorolyov** [comment]
merged in BE-8033.
